# Generated by Django 5.1.7 on 2025-03-19 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_producto'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='producto',
            unique_together={('categoria', 'nombre')},
        ),
    ]
